
name: check SonarQube
on: push

jobs:
  owasp-zap:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.time.ir'
          docker_name: 'owasp/zap2docker-stable'
          fail_action: true
          allow_issue_writing: true

